modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/squeek502/AppleSkin"

[[mods]]
modId="appleskin"
version="${version}"
displayName="AppleSkin"
#updateJSONURL=""
displayURL="https://github.com/squeek502/AppleSkin"
#logoFile="appleskin.png"
authors="squeek"
description="Adds various food-related HUD improvements"

[[dependencies.appleskin]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.43,)"
    ordering="AFTER"
    side="CLIENT"