modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/squeek502/AppleSkin"

[[mods]]
modId="appleskin"
version="${version}"
displayName="AppleSkin"
#updateJSONURL=""
displayURL="https://github.com/squeek502/AppleSkin"
#logoFile="appleskin.png"
authors="squeek"
description="Adds various food-related HUD improvements"

# Required for ObfuscationReflectionHelper change in 25.0.110
[[dependencies.appleskin]]
    modId="forge"
    mandatory=true
    versionRange="[25.0.110,)"
    ordering="NONE"
    side="BOTH"
